import type { Departure } from '@types'
import { FlightDirections } from '@types'

export const exampleDepartures: Departure[] = [
  {
    flightDirection: FlightDirections.Departure,
    scheduledDepartureDateTime: '2022-08-22T10:30:00',
    scheduledArrivalDateTime: '2022-08-22T01:00:00',
    estimatedDepartureDateTime: '2022-08-22T10:51:00',
    actualDepartureDateTime: '2022-08-22T10:49:00',
    arrivalAirport: {
      name: 'Charles de Gaulle Airport',
      cityName: 'Paris',
      countryName: 'France',
      code: 'CDG',
    },
    departureAirport: {
      name: 'Manchester Airport',
      cityName: 'Manchester',
      countryName: 'United Kingdom',
      code: 'MAN',
    },
    flightNumber: 'AF1669',
    airline: {
      name: 'Air France',
      code: 'AF',
    },
    departureGate: {
      name: 'Gate A5',
      number: 'A5',
      action: 'Final Call',
    },
    arrivalTerminal: null,
    departureTerminal: '2',
    status: 'Departed 10:49',
  },
  {
    flightDirection: FlightDirections.Departure,
    scheduledDepartureDateTime: '2022-08-22T10:40:00',
    scheduledArrivalDateTime: '2022-08-22T01:00:00',
    estimatedDepartureDateTime: '2022-08-22T11:30:00',
    actualDepartureDateTime: null,
    arrivalAirport: {
      name: 'Istanbul Airport',
      cityName: 'Istanbul',
      countryName: 'Turkey',
      code: 'IST',
    },
    departureAirport: {
      name: 'Manchester Airport',
      cityName: 'Manchester',
      countryName: 'United Kingdom',
      code: 'MAN',
    },
    flightNumber: 'TK1994',
    airline: {
      name: 'Turkish Airlines',
      code: 'TK',
    },
    departureGate: {
      name: 'Gate 31',
      number: '31',
      action: 'Final Call',
    },
    arrivalTerminal: null,
    departureTerminal: '1',
    status: 'Final Call - Gate 31',
  },
  {
    flightDirection: FlightDirections.Departure,
    scheduledDepartureDateTime: '2022-08-22T10:45:00',
    scheduledArrivalDateTime: '2022-08-22T01:00:00',
    estimatedDepartureDateTime: '2022-08-22T10:45:00',
    actualDepartureDateTime: '2022-08-22T10:45:00',
    arrivalAirport: {
      name: 'Franz Josef Strauss Airport',
      cityName: 'Munich',
      countryName: 'Germany',
      code: 'MUC',
    },
    departureAirport: {
      name: 'Manchester Airport',
      cityName: 'Manchester',
      countryName: 'United Kingdom',
      code: 'MAN',
    },
    flightNumber: 'LH2501',
    airline: {
      name: 'Lufthansa',
      code: 'LH',
    },
    departureGate: {
      name: 'Gate 25',
      number: '25',
      action: 'Final Call',
    },
    arrivalTerminal: null,
    departureTerminal: '1',
    status: 'Departed 10:45',
  },
  {
    flightDirection: FlightDirections.Departure,
    scheduledDepartureDateTime: '2022-08-22T10:50:00',
    scheduledArrivalDateTime: '2022-08-22T01:00:00',
    estimatedDepartureDateTime: '2022-08-22T10:50:00',
    actualDepartureDateTime: '2022-08-22T10:50:00',
    arrivalAirport: {
      name: 'Isle of Man Airport',
      cityName: 'Isle Of Man',
      countryName: 'United Kingdom',
      code: 'IOM',
    },
    departureAirport: {
      name: 'Manchester Airport',
      cityName: 'Manchester',
      countryName: 'United Kingdom',
      code: 'MAN',
    },
    flightNumber: 'LM694',
    airline: {
      name: 'Loganair',
      code: 'LM',
    },
    departureGate: {
      name: 'Gate 37',
      number: '37',
      action: 'Final Call',
    },
    arrivalTerminal: null,
    departureTerminal: '3',
    status: 'Departed 10:50',
  },
  {
    flightDirection: FlightDirections.Departure,
    scheduledDepartureDateTime: '2022-08-22T10:55:00',
    scheduledArrivalDateTime: '2022-08-22T01:00:00',
    estimatedDepartureDateTime: '2022-08-22T11:20:00',
    actualDepartureDateTime: null,
    arrivalAirport: {
      name: 'Lisbon Portela Airport',
      cityName: 'Lisbon',
      countryName: 'Portugal',
      code: 'LIS',
    },
    departureAirport: {
      name: 'Manchester Airport',
      cityName: 'Manchester',
      countryName: 'United Kingdom',
      code: 'MAN',
    },
    flightNumber: 'TP1317',
    airline: {
      name: 'TAP Air Portugal',
      code: 'TP',
    },
    departureGate: {
      name: 'Gate 22',
      number: '22',
      action: 'Final Call',
    },
    arrivalTerminal: null,
    departureTerminal: '1',
    status: 'Final Call - Gate 22',
  },
  {
    flightDirection: FlightDirections.Departure,
    scheduledDepartureDateTime: '2022-08-22T11:00:00',
    scheduledArrivalDateTime: '2022-08-22T01:00:00',
    estimatedDepartureDateTime: '2022-08-22T11:25:00',
    actualDepartureDateTime: null,
    arrivalAirport: {
      name: 'Orlando International Airport',
      cityName: 'Orlando',
      countryName: 'United States',
      code: 'MCO',
    },
    departureAirport: {
      name: 'Manchester Airport',
      cityName: 'Manchester',
      countryName: 'United Kingdom',
      code: 'MAN',
    },
    flightNumber: 'EI35',
    airline: {
      name: 'Aer Lingus',
      code: 'EI',
    },
    departureGate: {
      name: 'Gate 208',
      number: '208',
      action: 'Final Call',
    },
    arrivalTerminal: null,
    departureTerminal: '2',
    status: 'Final Call - Gate 208',
  },
  {
    flightDirection: FlightDirections.Departure,
    scheduledDepartureDateTime: '2022-08-22T11:00:00',
    scheduledArrivalDateTime: '2022-08-22T01:00:00',
    estimatedDepartureDateTime: '2022-08-22T11:00:00',
    actualDepartureDateTime: '2022-08-22T10:58:00',
    arrivalAirport: {
      name: 'Geneve Airport',
      cityName: 'Geneva',
      countryName: 'Switzerland',
      code: 'GVA',
    },
    departureAirport: {
      name: 'Manchester Airport',
      cityName: 'Manchester',
      countryName: 'United Kingdom',
      code: 'MAN',
    },
    flightNumber: 'EZY1949',
    airline: {
      name: 'easyJet',
      code: 'EZY',
    },
    departureGate: {
      name: 'Gate 3A',
      number: '3A',
      action: 'Final Call',
    },
    arrivalTerminal: null,
    departureTerminal: '1',
    status: 'Departed 10:58',
  },
]

export const exampleDeparture = {
  flightDirection: FlightDirections.Departure,
  scheduledDepartureDateTime: '2022-08-22T10:45:00',
  scheduledArrivalDateTime: '2022-08-22T01:00:00',
  estimatedDepartureDateTime: '2022-08-22T10:45:00',
  actualDepartureDateTime: '2022-08-22T10:45:00',
  arrivalAirport: {
    name: 'Franz Josef Strauss Airport',
    cityName: 'Munich',
    countryName: 'Germany',
    code: 'MUC',
  },
  departureAirport: {
    name: 'Manchester Airport',
    cityName: 'Manchester',
    countryName: 'United Kingdom',
    code: 'MAN',
  },
  flightNumber: 'LH2501',
  airline: {
    name: 'Lufthansa',
    code: 'LH',
  },
  departureGate: {
    name: 'Gate 25',
    number: '25',
    action: 'Final Call',
  },
  arrivalTerminal: null,
  departureTerminal: '1',
  status: 'Departed 10:45',
}
